# Generated by Django 3.2 on 2020-11-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0002_brain_lung'),
    ]

    operations = [
        migrations.AddField(
            model_name='brain',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.Comentario'),
        ),
    ]
