# Generated by Django 3.2 on 2020-11-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0003_brain_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='brain',
            name='avaliacoes',
            field=models.ManyToManyField(to='avaliacoes.Avaliacao'),
        ),
    ]
