# Generated by Django 3.2 on 2020-11-24 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0005_brain_enderecos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brain',
            name='enderecos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco'),
        ),
    ]
