# Generated by Django 3.2 on 2020-11-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_brain_enderecos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brain',
            old_name='nome',
            new_name='user',
        ),
    ]
