# Generated by Django 3.2 on 2020-11-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_user_brain_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brain',
            old_name='nome',
            new_name='username',
        ),
    ]
