# Generated by Django 3.2 on 2020-11-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_nome_brain_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brain',
            old_name='username',
            new_name='nome',
        ),
    ]
