# Generated by Django 3.2 on 2020-11-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_username_brain_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brain',
            old_name='nome',
            new_name='usuario',
        ),
    ]
