# Generated by Django 3.2 on 2020-11-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_usuario_brain_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brain',
            name='aprovado',
            field=models.BooleanField(default=True),
        ),
    ]
