# Generated by Django 3.2 on 2020-11-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_brain_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='brain',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='brain'),
        ),
    ]
