# Generated by Django 3.2 on 2020-11-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_alter_comentario_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario',
            new_name='user',
        ),
    ]
