# Generated by Django 3.2 on 2020-11-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_rename_user_comentario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='username',
            new_name='nome',
        ),
    ]
