# Generated by Django 3.2 on 2020-11-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0005_rename_username_comentario_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='nome',
            new_name='usuario',
        ),
    ]
