# Generated by Django 3.2 on 2020-11-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lung',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Lung'),
        ),
    ]
